### PR TITLE
Miner logs

### PR DESCRIPTION
**Pull request by raggi**
miner: improve logs for readability & diagnosis
 
    - exclude private key material so it's safer to paste logs
    - include block number in most output, aiding sync diagnosis
    - include current nonce so nonce distribution can be validated

### CODE REVIEW

**Comment by liamnoroian** [comment]
Acts as though it's mining starting with block 1 with MINING_DISABLED='TRUE' on ubuntu 20.04. Is this intended behavior?

**Comment by raggi** [comment]
I'm not sure what's going on there, start_mining shouldn't be called at all if mining is disabled. I'm not sure this patch alters that condition. Can you provide repro steps?

**Comment by liamnoroian** [comment]
> I'm not sure what's going on there, start_mining shouldn't be called at all if mining is disabled. I'm not sure this patch alters that condition. Can you provide repro steps?

- Clone xgt
- git checkout miner-logs
- rake clean configure make
- set seed_host to fh.rag.pub:2001
- rake run

**Comment by raggi** [comment]
If mining is enabled, as it is by default in the Rakefile, then mining will start immediately, that's existing behavior. The only change here is that it's making it obvious that it's block 0 that it's mining, but the code was already taking that action. The log message is accurate, that is what it's doing - and yes it's undesirable for fresh nodes to do this, but fixing the behavior is a different patch.

**Comment by liamnoroian** [comment]
Apologies, this is with mining disabled in the rakefile. In that case it should sync up to head, right?

**Comment by raggi** [comment]
I can not reproduce, can you please provide the exact commands you're using, and also validate that the configuration produced by the rakefile contains `enable-stale-production = false`. Here it does, and mining does not start:

```
% rake run MINING_DISABLED=TRUE XGT_SEED_HOST=xgt.rag.pub:2001 FLUSH_TESTNET=TRUE
rm -rf ../xgt-build/chain-data-0
mkdir -p ../xgt-build/chain-data-0
log-console-appender = {"appender":"stderr","stream":"std_error"}
log-file-appender = {"appender":"logfile","file":"logfile.log"}
log-logger = {"name":"default","level":"debug","appender":"stderr"}
log-logger = {"name":"default","level":"debug","appender":"logfile"}
#log-logger = {"name":"sync","level":"debug","appender":"stderr"}
#log-logger = {"name":"sync","level":"debug","appender":"logfile"}
#log-logger = {"name":"p2p","level":"debug","appender":"stderr"}
#log-logger = {"name":"p2p","level":"debug","appender":"logfile"}

backtrace = yes
plugin = chain p2p webserver witness database_api transaction_api block_api wallet_by_key wallet_history wallet_history_api wallet_by_key_api

shared-file-dir = "blockchain"
shared-file-size = 12G
p2p-endpoint = 0.0.0.0:2001
p2p-seed-node = xgt.rag.pub:2001
webserver-http-endpoint = 0.0.0.0:8751

miner = ["XGT0000000000000000000000000000000000000000","5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n"]
mining-threads = 1
witness = "XGT0000000000000000000000000000000000000000"
private-key = 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n
mining-reward-key = 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n

enable-stale-production = false
required-participation = 0

cd ../xgt-build/chain-data-0 && ../programs/xgtd/xgtd --data-dir=.
2814450ms database.cpp:529              set_chain_id         ] xgt_chain_id: 4e08b752aff5f66e1339cb8c0a8bca14c4ebb238655875db7dade86349091197
2814452ms webserver_plugin.cpp:343      plugin_initialize    ] configured with 32 thread pool size
2814453ms webserver_plugin.cpp:352      plugin_initialize    ] configured http to listen on 0.0.0.0:8751
2814453ms witness_plugin.cpp:470        plugin_initialize    ] Initializing witness plugin
2814453ms witness_plugin.cpp:475        plugin_initialize    ] my->_witnesses []
2814453ms database.cpp:541              set_witnesses        ] ws: ["XGT0000000000000000000000000000000000000000"]
2814453ms key_conversion.cpp:52         wif_to_key           ] ?????? libraries/utilities/key_conversion.cpp:52
2814453ms transaction_status_plugin.cpp:262 plugin_initialize    ] transaction_status: plugin_initialize() begin
2814453ms transaction_status_plugin.cpp:289 plugin_initialize    ] transaction status initializing
2814453ms transaction_status_plugin.cpp:290 plugin_initialize    ]   -> nominal block depth: 64000
2814453ms transaction_status_plugin.cpp:291 plugin_initialize    ]   -> actual block depth: 64720
2814453ms transaction_status_plugin.cpp:292 plugin_initialize    ]   -> nominal track after block: 0
2814453ms transaction_status_plugin.cpp:293 plugin_initialize    ]   -> actual track after block: 0
2814453ms transaction_status_plugin.cpp:297 plugin_initialize    ] Transaction status tracking activated
2814453ms transaction_status_plugin.cpp:308 plugin_initialize    ] transaction_status: plugin_initialize() end
2814454ms wallet_by_key_plugin.cpp:298  plugin_initialize    ] Initializing wallet_by_key plugin
------------------------------------------------------

            STARTING XGT NETWORK

------------------------------------------------------
network type: mainnet
address prefix: XGT
genesis wallet name: XGT0000000000000000000000000000000000000000
genesis public key: XGT7dDoJbrmueAw431pPbjLDoRhqFCC5Xs5o6f1cZLepWEpkcy3Tc
chain id: 4e08b752aff5f66e1339cb8c0a8bca14c4ebb238655875db7dade86349091197
blockchain version: 0.0.0
genesis_time: 2020-04-14T04:53:35
now: 2021-06-30T00:46:54
xgt_max_witnesses: 10
xgt_max_voted_witnesses: 0
xgt_max_miner_witnesses: 10
------------------------------------------------------
2814454ms main.cpp:116                  main                 ] Backtrace on segfault is enabled.
2814454ms chain_plugin.cpp:476          plugin_startup       ] Starting chain with shared_file_size: 12884901888 bytes
2814454ms chain_plugin.cpp:617          plugin_startup       ] Opening shared memory from /home/raggi/src/github.com/xgt-network/xgt-build/chain-data-0/./blockchain
2814454ms database.cpp:146              open                 ] database::open
2814454ms database.cpp:155              open                 ] database::open setting up global property object...
2814455ms database.cpp:1403             init_genesis         ] !!!!!! Preparing to create genesis account...
2814476ms database.cpp:171              open                 ] database::open setting up block log...
2814476ms database.cpp:179              open                 ] database::open setting up database...
2814476ms database.cpp:201              open                 ] database::open check for reindex...
2814476ms database.cpp:212              open                 ] database::open initialize versioning...
2814476ms database.cpp:219              open                 ] database::open initialize benchmarking...
2814476ms database.cpp:228              open                 ] database::open finish opening...
2814476ms chain_plugin.cpp:634          plugin_startup       ] Started on blockchain with 0 blocks
2814477ms p2p_plugin.cpp:654            operator()           ] Configuring P2P to listen at 0.0.0.0:2001
2814477ms p2p_plugin.cpp:662            operator()           ] P2P adding seed node 198.74.48.55:2001
2814478ms p2p_plugin.cpp:682            operator()           ] Listening on P2P network...
2814478ms p2p_plugin.cpp:685            operator()           ] Connecting to P2P network...
2814478ms p2p_plugin.cpp:694            operator()           ] P2P node listening at 0.0.0.0:2001
2814478ms p2p_plugin.cpp:696            plugin_startup       ] P2P Plugin started
2814478ms witness_plugin.cpp:539        plugin_startup       ] witness plugin:  plugin_startup() begin
2814478ms webserver_plugin.cpp:155      operator()           ] start processing http thread
2814478ms witness_plugin.cpp:558        plugin_startup       ] witness plugin:  plugin_startup() end
2814478ms webserver_plugin.cpp:165      operator()           ] start listening for http requests
2814479ms transaction_status_plugin.cpp:316 plugin_startup       ] transaction_status: plugin_startup() begin
2814479ms transaction_status_plugin.cpp:330 plugin_startup       ] transaction_status: plugin_startup() end
2815028ms database.cpp:837              _push_block          ] Pushing new block #1 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:03 at time 2021-06-30T00:46:55
2815028ms database.cpp:1553             check_free_memory    ] Free memory is now 11G. Current block number: 1
2815028ms database.cpp:837              _push_block          ] Pushing new block #2 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:18 at time 2021-06-30T00:46:55
2815028ms database.cpp:837              _push_block          ] Pushing new block #3 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:19 at time 2021-06-30T00:46:55
2815029ms database.cpp:837              _push_block          ] Pushing new block #4 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:23 at time 2021-06-30T00:46:55
2815029ms database.cpp:837              _push_block          ] Pushing new block #5 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:29 at time 2021-06-30T00:46:55
2815030ms database.cpp:837              _push_block          ] Pushing new block #6 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:31 at time 2021-06-30T00:46:55
2815030ms database.cpp:837              _push_block          ] Pushing new block #7 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:34 at time 2021-06-30T00:46:55
2815030ms database.cpp:837              _push_block          ] Pushing new block #8 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:35 at time 2021-06-30T00:46:55
2815031ms database.cpp:837              _push_block          ] Pushing new block #9 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:36 at time 2021-06-30T00:46:55
2815031ms database.cpp:837              _push_block          ] Pushing new block #10 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:39 at time 2021-06-30T00:46:55
2815031ms database.cpp:837              _push_block          ] Pushing new block #11 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:42 at time 2021-06-30T00:46:55
2815032ms database.cpp:837              _push_block          ] Pushing new block #12 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:46 at time 2021-06-30T00:46:55
2815032ms database.cpp:837              _push_block          ] Pushing new block #13 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:47 at time 2021-06-30T00:46:55
2815032ms database.cpp:837              _push_block          ] Pushing new block #14 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:48 at time 2021-06-30T00:46:55
2815033ms database.cpp:837              _push_block          ] Pushing new block #15 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:48 at time 2021-06-30T00:46:55
2815033ms database.cpp:837              _push_block          ] Pushing new block #16 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:21:59 at time 2021-06-30T00:46:55
2815033ms database.cpp:837              _push_block          ] Pushing new block #17 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:04 at time 2021-06-30T00:46:55
2815034ms database.cpp:837              _push_block          ] Pushing new block #18 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:06 at time 2021-06-30T00:46:55
2815034ms database.cpp:837              _push_block          ] Pushing new block #19 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:21 at time 2021-06-30T00:46:55
2815034ms database.cpp:837              _push_block          ] Pushing new block #20 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:22 at time 2021-06-30T00:46:55
2815035ms database.cpp:837              _push_block          ] Pushing new block #21 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:22 at time 2021-06-30T00:46:55
2815035ms database.cpp:837              _push_block          ] Pushing new block #22 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:25 at time 2021-06-30T00:46:55
2815036ms database.cpp:837              _push_block          ] Pushing new block #23 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:26 at time 2021-06-30T00:46:55
2815036ms database.cpp:837              _push_block          ] Pushing new block #24 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:28 at time 2021-06-30T00:46:55
2815036ms database.cpp:837              _push_block          ] Pushing new block #25 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:30 at time 2021-06-30T00:46:55
2815037ms database.cpp:837              _push_block          ] Pushing new block #26 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:30 at time 2021-06-30T00:46:55
2815037ms database.cpp:837              _push_block          ] Pushing new block #27 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:33 at time 2021-06-30T00:46:55
2815037ms database.cpp:837              _push_block          ] Pushing new block #28 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:41 at time 2021-06-30T00:46:55
2815038ms database.cpp:837              _push_block          ] Pushing new block #29 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:50 at time 2021-06-30T00:46:55
2815038ms database.cpp:837              _push_block          ] Pushing new block #30 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:55 at time 2021-06-30T00:46:55
2815038ms database.cpp:837              _push_block          ] Pushing new block #31 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:22:58 at time 2021-06-30T00:46:55
2815039ms database.cpp:837              _push_block          ] Pushing new block #32 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:02 at time 2021-06-30T00:46:55
2815039ms database.cpp:837              _push_block          ] Pushing new block #33 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:09 at time 2021-06-30T00:46:55
2815039ms database.cpp:837              _push_block          ] Pushing new block #34 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:11 at time 2021-06-30T00:46:55
2815040ms database.cpp:837              _push_block          ] Pushing new block #35 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:16 at time 2021-06-30T00:46:55
2815040ms database.cpp:837              _push_block          ] Pushing new block #36 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:16 at time 2021-06-30T00:46:55
2815040ms database.cpp:837              _push_block          ] Pushing new block #37 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:16 at time 2021-06-30T00:46:55
2815041ms database.cpp:837              _push_block          ] Pushing new block #38 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:18 at time 2021-06-30T00:46:55
2815041ms database.cpp:837              _push_block          ] Pushing new block #39 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:18 at time 2021-06-30T00:46:55
2815041ms database.cpp:837              _push_block          ] Pushing new block #40 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:21 at time 2021-06-30T00:46:55
2815042ms database.cpp:837              _push_block          ] Pushing new block #41 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:22 at time 2021-06-30T00:46:55
2815042ms database.cpp:837              _push_block          ] Pushing new block #42 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:22 at time 2021-06-30T00:46:55
2815042ms database.cpp:837              _push_block          ] Pushing new block #43 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:24 at time 2021-06-30T00:46:55
2815043ms database.cpp:837              _push_block          ] Pushing new block #44 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:26 at time 2021-06-30T00:46:55
2815043ms database.cpp:837              _push_block          ] Pushing new block #45 from XGT0000000000000000000000000000000000000000 with timestamp 2021-06-07T21:23:36 at time 2021-06-30T00:46:55

```

**Comment by liamnoroian** [comment]
Ah found something. `enable-stale-production` was set to true, so I checked the rakefile and it looked like the ternary operator used to set that variable with mining_disabled?` was producing the opposite result. 

`145: enable-stale-production = #{mining_disabled? ? 'false' : 'true'}`

This is correct, and I'm not sure exactly what went wrong previously. 
With enable-stale production set correctly the node syncs properly.

**Pull request merged**
